/**
  You need to create an express HTTP server in Node.js which will handle the logic of a todo list app.
  - Don't use any database, just store all the data in an array to store the todo list data (in-memory)
  - Hard todo: Try to save responses in files, so that even if u exit the app and run it again, the data remains (similar to databases)

  Each todo has a title and a description. The title is a string and the description is a string.
  Each todo should also get an unique autogenerated id every time it is created
  The expected API endpoints are defined below,
  1.GET /todos - Retrieve all todo items
    Description: Returns a list of all todo items.
    Response: 200 OK with an array of todo items in JSON format.
    Example: GET http://localhost:3000/todos
    
  2.GET /todos/:id - Retrieve a specific todo item by ID
    Description: Returns a specific todo item identified by its ID.
    Response: 200 OK with the todo item in JSON format if found, or 404 Not Found if not found.
    Example: GET http://localhost:3000/todos/123
    
  3. POST /todos - Create a new todo item
    Description: Creates a new todo item.
    Request Body: JSON object representing the todo item.
    Response: 201 Created with the ID of the created todo item in JSON format. eg: {id: 1}
    Example: POST http://localhost:3000/todos
    Request Body: { "title": "Buy groceries", "completed": false, description: "I should buy groceries" }
    
  4. PUT /todos/:id - Update an existing todo item by ID
    Description: Updates an existing todo item identified by its ID.
    Request Body: JSON object representing the updated todo item.
    Response: 200 OK if the todo item was found and updated, or 404 Not Found if not found.
    Example: PUT http://localhost:3000/todos/123
    Request Body: { "title": "Buy groceries", "completed": true }
    
  5. DELETE /todos/:id - Delete a todo item by ID
    Description: Deletes a todo item identified by its ID.
    Response: 200 OK if the todo item was found and deleted, or 404 Not Found if not found.
    Example: DELETE http://localhost:3000/todos/123

    - For any other route not defined in the server return 404

  Testing the server - run `npm run test-todoServer` command in terminal
 */
  const express = require('express');
  const bodyParser = require('body-parser');
  
  const app = express();
  
  app.use(bodyParser.json());

  let todos = [];

  
// request method for reading all the todos from todo app
  app.get("/todos", (req, res)=>{
    res.status(200).json(todos);

  })

  // request method for reading a todo with a specific id
  app.get("/todos/:taskId", (req, res)=>{
    let taskIdd = req.params.taskId;
    if(requiredTodo(taskIdd)!=false){
    res.status(200).json(requiredTodo(taskIdd))
    }else{
      res.status(404).send("404 Not Found")
    }
  })
 
// request method for creating a new todo based on the 
// json matter present on the body of the html page
  app.post("/todos", (req, res)=>{
    let new_todo = req.body;
    let generatednewId = generateId();
    let todo = {
      id: generatednewId,
      title: new_todo.title,
      description: new_todo.description
    }
    todos.push(todo);
    res.status(201).json({id: generatednewId})
  })

// request method for updating a task of a specific id
app.put("/todos/:taskId", (req, res)=>{
  let updated_todo = req.body;
  let idUpdateTask = req.params.taskId;
  let returnedVal = updateTodo(idUpdateTask, updated_todo);
  if(returnedVal !=false){
    res.status(200).send("the specific todo was updated");
  }else{
    res.status(404).send("404 Not Found")
  }
})


// request method for deleting a task fo a specific id

app.delete("/todos/:taskId", (req, res)=>{
  let deleteId = req.params.taskId;
  let returnedVal = deleteTodo(deleteId);
  if(returnedVal!=false){
    res.status(200).send("deleted the todo successfully!");
  }else{
    res.status(404).send("404 Not Found")
  }
})


app.use((req, res)=>{
  res.status(404).send("404 Not Found")
})


  // function that gets the specific todo from todos list
  function requiredTodo(taskId){
    for(let i=0; i<= todos.length-1; i++){
      if(Number(taskId) === todos[i].id){
        return {
          id: Number(taskId),
          title: todos[i].title,
          description: todos[i].description
        };
      }
    }
    return false;
  }


  // function that takes two arguments:
  // the todolist and the json matter of update info todo

  function updateTodo(taskId, updatedJson){

    let updatedTitle = updatedJson["title"];
    let updatedDesc = updatedJson["description"];
    for(let i=0; i<=todos.length-1; i++){
      if(Number(taskId)===todos[i]["id"]){
        todos[i]["title"] = updatedTitle;
        todos[i]["description"] = updatedDesc;
        return true;
      }
    }
    return false;
  }
  

  function deleteTodo(deleteId){
    for(let i=0; i<=todos.length-1; i++){
      if(Number(deleteId) === todos[i]["id"]){
        todos.splice(i, 1);
        return true;
      }
    }
    return false;
  }

  function generateId(){
    return Math.floor(Math.random() * 1000000);
  }

if (require.main === module) {
  app.listen(3000);
}

  module.exports = app;


